# Fix script - Restore missing methods
with open('block_blast_copilot.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find and fix the broken section (lines 840-897)
# Remove duplicate code and add missing methods

fixed_lines = lines[:840]  # Keep everything before line 840

# Add correct methods
fixed_lines.extend([
    "                print(f\"Lỗi trong copilot loop: {e}\")\r\n",
    "                import traceback\r\n",
    "                traceback.print_exc()\r\n",
    "                self.update_status(f\"❌ Error: {e}\")\r\n",
    "                time.sleep(2)\r\n",
    "    \r\n",
    "    def display_board_and_pieces(self):\r\n",
    "        \"\"\"Hiển thị board và pieces\"\"\"\r\n",
    "        # Board - 220px như code gốc\r\n",
    "        if self.current_board is not None:\r\n",
    "            img = self.create_board_image(self.current_board)\r\n",
    "            max_size = 220\r\n",
    "            w0, h0 = img.size\r\n",
    "            ratio = min(max_size / w0, max_size / h0)\r\n",
    "            img = img.resize((int(w0 * ratio), int(h0 * ratio)), Image.Resampling.LANCZOS)\r\n",
    "            ph = ImageTk.PhotoImage(img)\r\n",
    "            self.board_label.configure(image=ph, text=\"\")\r\n",
    "            self.board_label.image = ph\r\n",
    "        \r\n",
    "        # Pieces - 60px như code gốc\r\n",
    "        if self.current_pieces:\r\n",
    "            for i, piece in enumerate(self.current_pieces[:3]):\r\n",
    "                img = self.create_piece_image(piece, cell_size=30)\r\n",
    "                max_size = 60\r\n",
    "                w0, h0 = img.size\r\n",
    "                if w0 == 0 or h0 == 0: continue\r\n",
    "                ratio = min(max_size / w0, max_size / h0)\r\n",
    "                img = img.resize((int(w0 * ratio), int(h0 * ratio)), Image.Resampling.LANCZOS)\r\n",
    "                ph = ImageTk.PhotoImage(img)\r\n",
    "                self.piece_labels[i].configure(image=ph, text=\"\")\r\n",
    "                self.piece_labels[i].image = ph\r\n",
    "    \r\n",
    "    def display_solutions(self):\r\n",
    "        \"\"\"Hiển thị solutions trong 3 cột - 150px như code gốc\"\"\"\r\n",
    "        for i, sol in enumerate(self.current_solutions[:3]):\r\n",
    "            if sol and 'piece' in sol:\r\n",
    "                img = self.create_solution_image(\r\n",
    "                    self.current_board, \r\n",
    "                    sol['piece'], \r\n",
    "                    sol['position']\r\n",
    "                )\r\n",
    "                # 150px như code gốc (không phải 220px)\r\n",
    "                max_size = 150\r\n",
    "                w0, h0 = img.size\r\n",
    "                ratio = min(max_size / w0, max_size / h0)\r\n",
    "                img = img.resize((int(w0 * ratio), int(h0 * ratio)), Image.Resampling.LANCZOS)\r\n",
    "                ph = ImageTk.PhotoImage(img)\r\n",
    "                self.sol_labels[i].configure(image=ph, text=\"\")\r\n",
    "                self.sol_labels[i].image = ph\r\n",
    "            else:\r\n",
    "                self.sol_labels[i].configure(text=\"No solution\", image=\"\")\r\n",
    "    \r\n",
    "    def update_status(self, text: str):\r\n",
    "        \"\"\"Cập nhật status label\"\"\"\r\n",
    "        self.root.after(0, lambda: self.status_label.configure(text=text))\r\n",
    "    \r\n",
    "    def create_board_image(self, board):\r\n",
    "        \"\"\"Tạo ảnh board\"\"\"\r\n",
    "        h, w = board.shape\r\n",
    "        cell = 50\r\n",
    "        base = np.ones((h * cell, w * cell, 3), dtype=np.uint8) * 30\r\n",
    "        for r in range(h):\r\n",
    "            for c in range(w):\r\n",
    "                color = (50, 50, 50) if board[r, c] == 0 else (100, 180, 100)\r\n",
    "                y1, x1 = r * cell, c * cell\r\n",
    "                y2, x2 = (r + 1) * cell, (c + 1) * cell\r\n",
    "                base[y1:y2, x1:x2] = color\r\n",
    "                cv2.rectangle(base, (x1, y1), (x2-1, y2-1), (80, 80, 80), 1)\r\n",
    "        return Image.fromarray(cv2.cvtColor(base, cv2.COLOR_BGR2RGB))\r\n",
    "    \r\n",
    "    def create_piece_image(self, piece, cell_size=25):\r\n",
    "        \"\"\"Tạo ảnh piece - cell_size nhỏ hơn\"\"\"\r\n",
    "        h, w = piece.shape\r\n",
    "        base = np.ones((h * cell_size, w * cell_size, 3), dtype=np.uint8) * 30\r\n",
    "        for r in range(h):\r\n",
    "            for c in range(w):\r\n",
    "                color = (50, 50, 50) if piece[r, c] == 0 else (100, 180, 100)\r\n",
    "                y1, x1 = r * cell_size, c * cell_size\r\n",
    "                y2, x2 = (r + 1) * cell_size, (c + 1) * cell_size\r\n",
    "                base[y1:y2, x1:x2] = color\r\n",
    "                cv2.rectangle(base, (x1, y1), (x2-1, y2-1), (80, 80, 80), 1)\r\n",
    "        return Image.fromarray(base)\r\n",
    "    \r\n",
    "    def create_solution_image(self, board, piece, pos):\r\n",
    "        \"\"\"Tạo ảnh solution với highlight\"\"\"\r\n",
    "        b = board.copy()\r\n",
    "        r0, c0 = pos\r\n",
    "        for r in range(piece.shape[0]):\r\n",
    "            for c in range(piece.shape[1]):\r\n",
    "                if piece[r, c] == 1:\r\n",
    "                    br, bc = r0 + r, c0 + c\r\n",
    "                    if 0 <= br < b.shape[0] and 0 <= bc < b.shape[1]:\r\n",
    "                        b[br, bc] = 9\r\n",
    "        \r\n",
    "        h, w = b.shape\r\n",
    "        cell = 50\r\n",
    "        base = np.ones((h * cell, w * cell, 3), dtype=np.uint8) * 30\r\n",
    "        for r in range(h):\r\n",
    "            for c in range(w):\r\n",
    "                if b[r, c] == 0:\r\n",
    "                    color = (50, 50, 50)\r\n",
    "                elif b[r, c] == 9:\r\n",
    "                    color = (100, 200, 255)  # Highlight xanh dương\r\n",
    "                else:\r\n",
    "                    color = (100, 180, 100)\r\n",
    "                y1, x1 = r * cell, c * cell\r\n",
    "                y2, x2 = (r + 1) * cell, (c + 1) * cell\r\n",
    "                base[y1:y2, x1:x2] = color\r\n",
    "                cv2.rectangle(base, (x1, y1), (x2-1, y2-1), (80, 80, 80), 1)\r\n",
    "        return Image.fromarray(cv2.cvtColor(base, cv2.COLOR_BGR2RGB))\r\n",
    "    \r\n",
    "    def run(self):\r\n",
    "        self.root.mainloop()\r\n",
    "\r\n",
    "def main():\r\n",
    "    print(\"=== BLOCK BLAST COPILOT MODE ===\")\r\n",
    "    print(\"Tích hợp vision logic từ code gốc\")\r\n",
    "    print(\"Chỉ setup 1 lần, sau đó tự động chụp mỗi 8s\")\r\n",
    "    app = CopilotGUI()\r\n",
    "    app.run()\r\n",
    "\r\n",
    "if __name__ == \"__main__\":\r\n",
    "    main()\r\n",
])

# Write fixed file
with open('block_blast_copilot.py', 'w', encoding='utf-8') as f:
    f.writelines(fixed_lines)

print("Fixed! Restored all methods with correct sizes:")
print("- Board: 220px")
print("- Pieces: 60px")
print("- Solutions: 150px")
